export const data = JSON.parse("{\"key\":\"v-744ccd44\",\"path\":\"/src/\",\"title\":\"🍑目录\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"🍑目录\",\"index\":false,\"category\":[\"使用指南\"],\"description\":\"目录 - 🍅JavaSE - 🥥JavaWeb - 🥝基础框架 - 🥑基础微服务\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://github.com/Beisheng8888/blog/src/\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"Mr.Jh\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"🍑目录\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"目录 - 🍅JavaSE - 🥥JavaWeb - 🥝基础框架 - 🥑基础微服务\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"Mr.Jh\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"🍑目录\\\",\\\"image\\\":[\\\"\\\"],\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"Mr.Jh\\\",\\\"url\\\":\\\"https://github.com/Beisheng8888\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"目录\",\"slug\":\"目录\",\"link\":\"#目录\",\"children\":[]},{\"level\":2,\"title\":\"- 🍅JavaSE\",\"slug\":\"🍅javase\",\"link\":\"#🍅javase\",\"children\":[]},{\"level\":2,\"title\":\"- 🥥JavaWeb\",\"slug\":\"🥥javaweb\",\"link\":\"#🥥javaweb\",\"children\":[]},{\"level\":2,\"title\":\"- 🥝基础框架\",\"slug\":\"🥝基础框架\",\"link\":\"#🥝基础框架\",\"children\":[]},{\"level\":2,\"title\":\"- 🥑基础微服务\",\"slug\":\"🥑基础微服务\",\"link\":\"#🥑基础微服务\",\"children\":[]},{\"level\":2,\"title\":\"- 🥒高级微服务\",\"slug\":\"🥒高级微服务\",\"link\":\"#🥒高级微服务\",\"children\":[]},{\"level\":2,\"title\":\"- 🥦扩展\",\"slug\":\"🥦扩展\",\"link\":\"#🥦扩展\",\"children\":[]},{\"level\":2,\"title\":\"- 🫐面试专题\",\"slug\":\"🫐面试专题\",\"link\":\"#🫐面试专题\",\"children\":[]}],\"readingTime\":{\"minutes\":0.23,\"words\":68},\"filePathRelative\":\"src/README.md\",\"excerpt\":\"<h2> 目录</h2>\\n<h2> - 🍅<a href=\\\"/blog/src/JavaSE/\\\" target=\\\"blank\\\">JavaSE</a></h2>\\n<h2> - 🥥<a href=\\\"/blog/src/JavaWeb/\\\" target=\\\"blank\\\">JavaWeb</a></h2>\\n<h2> - 🥝<a href=\\\"/blog/src/%E5%9F%BA%E7%A1%80%E6%A1%86%E6%9E%B6/\\\" target=\\\"blank\\\">基础框架</a></h2>\\n<h2> - 🥑<a href=\\\"/blog/src/%E5%9F%BA%E7%A1%80%E5%BE%AE%E6%9C%8D%E5%8A%A1/\\\" target=\\\"blank\\\">基础微服务</a></h2>\",\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
